## Notebook for trying out error and accuracy functions

given a predicted and a target output 

Typical loss functions (also called “objective functions” or “scoring functions”) include:

    Binary cross-entropy
    Categorical cross-entropy
    Sparse categorical cross-entropy
    Mean Squared Error (MSE)
    Mean Absolute Error (MAE)
    Standard Hinge
    Squared Hinge

In [38]:
import numpy as np 

#### Mean square 

In [39]:
pred = np.array([[0., 0.8], [0.3, 0.], [0., 0.5],  [0.5, 0.]])
tar  = np.array([[0., 1.], [0., 1.], [1., 0.], [1., 0.]])

print(np.sum( tar - pred  , axis=1))

[0.2 0.7 0.5 0.5]


❌ error the same even though entirely wrong class was activated 

#### Cross Entropy Loss

In [76]:
pred = np.array([[0., 0.8], [0.3, 0.], [0., 0.5],  [0.5, 0.]])
tar  = np.array([[0., 1.], [0., 1.], [1., 0.], [1., 0.]])

pred = np.array([[0., 0.8, 0.], [0.3, 0., 0.], [0., 0., 0.5],  [0.5, 0., 0.]])
tar  = np.array([[0., 1., 0.], [0., 1., 0.], [1., 0., 0.], [0., 1., 0.]])

epsilon = 1e-15  # Small constant to prevent log(0)

# Clip predicted probabilities to avoid log(0) or log(1)
pred = np.clip(pred, epsilon, 1 - epsilon)
tar = np.clip(tar, epsilon, 1 - epsilon)
losses = []
for p,t in zip(pred,tar):
    # Calculate cross-entropy loss
    print("here")
    print (t * np.log(p))# + (1 - t) * np.log(1 - p))
    loss = - np.sum(t * np.log(p))# + (1 - t) * np.log(1 - p))
   # print("loss", loss)
    # Normalize by the number of examples
    num_examples = len(tar)
   # print("num", num_examples)
    loss /= num_examples
    losses.append(loss)


def cross_entropy_loss(p, t):
    # Calculate cross-entropy loss
    
    return - np.sum(t * np.log(p), axis=1) / len(t)


def cross_entropy_loss_prime(p,t):
    # https://shivammehta25.github.io/posts/deriving-categorical-cross-entropy-and-softmax/
    return  np.sum(p- t, axis=1) / len(t)


print(losses)
print(cross_entropy_loss(pred,tar))
print(cross_entropy_loss_prime(pred,tar))

here
[-3.45387764e-14 -2.23143551e-01 -3.45387764e-14]
here
[-1.20397280e-15 -3.45387764e+01 -3.45387764e-14]
here
[-3.45387764e+01 -3.45387764e-14 -6.93147181e-16]
here
[-6.93147181e-16 -3.45387764e+01 -3.45387764e-14]
[0.055785887828569636, 8.634694098727671, 8.634694098727671, 8.634694098727671]
[0.05578589 8.6346941  8.6346941  8.6346941 ]
[0.05  0.175 0.125 0.125]


In [ ]:

pred = np.array([[0., 0.8, 0.], [0.3, 0., 0.], [0., 0., 0.5],  [0.5, 0., 0.]])
tar  = np.array([[0., 1., 0.], [0., 1., 0.], [1., 0., 0.], [0., 1., 0.]])

epsilon = 1e-15  # Small constant to prevent log(0)

# Clip predicted probabilities to avoid log(0) or log(1)
pred = np.clip(pred, epsilon, 1 - epsilon)
tar = np.clip(tar, epsilon, 1 - epsilon)
losses = []
for cIDX in pred[0]: # for class in classses 
    for p,t in zip(pred,tar):
        # Calculate cross-entropy loss
        loss = - np.sum(t * np.log(p) + (1 - t) * np.log(1 - p))
    # print("loss", loss)
        # Normalize by the number of examples
        num_examples = len(tar)
    # print("num", num_examples)
        loss /= num_examples
        losses.append(loss)
print(losses)

✅ highest error for [[1., 0.], [1., 0.], [0., 1.]] and [[0., 1.], [0., 1.], [1., 0.]] is 34.53917619362575

#### Coefficient of Determination

In [64]:
pred = np.array([[1., 0.], [1., 0.], [0., 1.]])
tar  = np.array([[0., 1.], [0., 1.], [1., 0.]])

corr_matrix = np.corrcoef(tar, pred)
corr = corr_matrix[0,1]
R_sq = corr**2
 
print(R_sq)

0.9999999999999998


In [65]:
pred = np.array([[0., 1.], [0., 1.], [1., 0.]])
tar  = np.array([[0., 1.], [0., 1.], [1., 0.]])

corr_matrix = np.corrcoef(tar, pred)
corr = corr_matrix[0,1]
R_sq = corr**2
 
print(R_sq)

0.9999999999999998


❌ does not take one-hot into account at all

In [43]:
prediction = np.array([[3.5409444e-09, 0.0000000e+00],
                        [3.6693652e-06, 0.0000000e+00],
                        [0.0000000e+00, 9.3634579e-01],
                        [3.8932901e-09, 0.0000000e+00],
                        [4.0344894e-06, 0.0000000e+00],
                        [4.7976482e-01, 0.0000000e+00],
                        [2.8737641e-09, 0.0000000e+00],
                        [2.9779881e-06, 0.0000000e+00],
                        [3.5413006e-01, 0.0000000e+00]])

prediction = np.array([[3.5409444e-09, 0.0000000e+00],
                        [3.6693652e-09, 0.0000000e+00],
                        [0.0000000e+00, 9.9993634579e-01],
                        [3.8932901e-09, 0.0000000e+00],
                        [4.0344894e-06, 0.0000000e+00],
                        [4.7976482e-09, 0.0000000e+00],
                        [2.8737641e-09, 0.0000000e+00],
                        [2.9779881e-09, 0.0000000e+00],
                        [3.5413006e-09, 0.0000000e+00]])

target = np.array([[0., 1.],
                    [0., 1.],
                    [0., 1.],
                    [0., 1.],
                    [0., 1.],
                    [0., 1.],
                    [0., 1.],
                    [0., 1.],
                    [0., 1.]])


sample_test_accuracy =  target == np.round(prediction, 0)
print(sample_test_accuracy)
sample_test_accuracy = np.mean(sample_test_accuracy)
print(sample_test_accuracy)

[[ True False]
 [ True False]
 [ True  True]
 [ True False]
 [ True False]
 [ True False]
 [ True False]
 [ True False]
 [ True False]]
0.5555555555555556
