## Gallery 

In [1]:
## basic imports ##

import pandas as pd
import numpy as np
import os
import matplotlib.pyplot as plt
import yaml 
from yaml.loader import UnsafeLoader
import os


## PRINTING

In [8]:
def load_weights():
        """load weights from yaml file
        
        Args:
            filename etc
        Returns:
            loaded_weights (numpy.ndarray): 
        """
        # opt 1: yaml
        file_name = f"config_weights.yaml"
        relative_path =  "\\..\\neurofuzzy_pkg\\fuzzyLayers\\weights"
        save_path = os.getcwd() +  relative_path # https://stackoverflow.com/questions/39125532/file-does-not-exist-in-jupyter-notebook
        full_path = os.path.join(save_path, file_name)
        assert  os.path.exists(full_path), f'Path {relative_path}/{file_name} does not exist'
        completeName = full_path#os.path.join(save_path, file_name)
        with open(completeName, 'r') as config_file:
            # Converts yaml document to python object
            config =yaml.load(config_file, Loader=UnsafeLoader)
            weights = np.array(config)
            print(type(weights))
            print(weights)
        
        # opt 2: np.save
        file_name = "config_weights"
        other_name = os.path.join(save_path, file_name)
        loaded_weights = np.load(other_name+'.npy')
      #  print("HERE")
        print(loaded_weights)
       # return weights
        return weights,loaded_weights

yaml_output, np_save_output = load_weights()
#print(len(test))
print((yaml_output==np_save_output).all())

print(np_save_output[:,1])

<class 'numpy.ndarray'>
[[0. 0.]
 [0. 1.]
 [0. 1.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 1.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 1.]
 [0. 0.]
 [0. 0.]
 [0. 1.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 1.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 1.]
 [0. 1.]
 [0. 0.]
 [0. 0.]
 [0. 1.]
 [0. 0.]
 [0. 1.]
 [0. 1.]
 [0. 0.]
 [0. 0.]
 [0. 1.]
 [0. 0.]
 [0. 0.]
 [0. 1.]
 [0. 0.]
 [0. 0.]
 [0. 1.]
 [0. 0.]
 [0. 0.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 0.]
 [0. 0.]
 [0. 1.]
 [0. 0.]
 [0. 1.]
 [0. 1.]
 [0. 0.]
 [0. 1.]
 [0. 1.]
 [0. 0.]
 [0. 1.]
 [0. 1.]
 [0. 0.]
 [0. 1.]
 [0. 1.]
 [0. 0.]
 [0. 0.]
 [0. 1.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 1.]
 [0. 1.]
 [0. 0.]
 [0. 0.]
 [0. 1.]
 [0. 0.]
 [0. 1.]
 [0. 1.]
 [0. 0.]
 [0. 0.]
 [0. 1.]
 [0.

In [5]:
file_name = 'config_weights.npy'
relative_path =   '/../data'

# get save path 
save_path = os.getcwd() +  relative_path # https://stackoverflow.com/questions/39125532/file-does-not-exist-in-jupyter-notebook
full_path = os.path.join(save_path, file_name)
assert  os.path.exists(full_path), f'Path {relative_path}/{file_name} does not exist'

# read via panda reader
df = pd.read_csv(full_path)
plt.show()
df.plot( figsize=(40, 20), subplots=True)

AssertionError: Path /../data/config_weights.npy does not exist

In [ ]:
# get save path 
file_name = f"config_mf.yaml"
relative_path =  "\\..\\neurofuzzy_pkg\\fuzzyLayers\\weights"

save_path = os.getcwd() +  relative_path # https://stackoverflow.com/questions/39125532/file-does-not-exist-in-jupyter-notebook
full_path = os.path.join(save_path, file_name)
assert  os.path.exists(full_path), f'Path {relative_path}/{file_name} does not exist'


with open(full_path, 'r') as config_file:
    # Converts yaml document to python object
    config =yaml.load(config_file, Loader=UnsafeLoader)
    config = dict(config)
    centers = config["centers"]
    widths = config["widths"]
    #  print(type(weights))
    print(centers)
    print(widths)

    # # opt 2: np.save
    # file_name = "config_weights"
    # other_name = os.path.join(save_path, file_name)
    # loaded_weights = np.load(other_name+'.npy')
    #print("self.centers")


[[2.0799093e+00 4.1598186e+00 6.2397280e+00]
 [1.3195513e-01 2.6391026e-01 3.9586538e-01]
 [6.7743905e-02 1.3548781e-01 2.0323171e-01]
 [6.3470137e-01 1.2694027e+00 1.9041041e+00]
 [2.1866634e-02 4.3733269e-02 6.5599903e-02]
 [3.9687304e+00 7.9374609e+00 1.1906192e+01]
 [1.1616948e+01 2.3233896e+01 3.4850845e+01]
 [2.4918666e-01 4.9837333e-01 7.4756002e-01]
 [8.2777828e-01 1.6555566e+00 2.4833348e+00]
 [1.6453721e-01 3.2907441e-01 4.9361163e-01]
 [2.6057458e+00 5.2114916e+00 7.8172374e+00]]
[[ 2.0799093   2.0799093   2.0799093 ]
 [ 0.13195513  0.13195513  0.13195513]
 [ 0.0677439   0.0677439   0.0677439 ]
 [ 0.6347014   0.6347014   0.6347014 ]
 [ 0.02186663  0.02186663  0.02186663]
 [ 3.9687304   3.9687304   3.9687304 ]
 [11.616948   11.616948   11.616948  ]
 [ 0.24918666  0.24918666  0.24918666]
 [ 0.8277783   0.8277783   0.8277783 ]
 [ 0.1645372   0.1645372   0.1645372 ]
 [ 2.6057458   2.6057458   2.6057458 ]]


In [ ]:
df = pd.read_csv(
    "https://archive.ics.uci.edu/ml/machine-learning-databases/wine-quality/winequality-red.csv", 
    delimiter=";")

print(df.head())

treshhold = np.mean(df['quality'])
print("tresh", treshhold)
#df['quality'] = df['quality'].apply(lambda x: x >= treshhold)
df['quality'] = df['quality'].apply(lambda x: int(x >= treshhold))


print(df.head())

   fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0            7.4              0.70         0.00             1.9      0.076   
1            7.8              0.88         0.00             2.6      0.098   
2            7.8              0.76         0.04             2.3      0.092   
3           11.2              0.28         0.56             1.9      0.075   
4            7.4              0.70         0.00             1.9      0.076   

   free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
0                 11.0                  34.0   0.9978  3.51       0.56   
1                 25.0                  67.0   0.9968  3.20       0.68   
2                 15.0                  54.0   0.9970  3.26       0.65   
3                 17.0                  60.0   0.9980  3.16       0.58   
4                 11.0                  34.0   0.9978  3.51       0.56   

   alcohol  quality  
0      9.4        5  
1      9.8        5  
2      9.8        5 

In [ ]:
file_name = 'bbdc_2023_AWI_data_develop_student_basic.csv'
relative_path =   '/../data'

# get save path 
save_path = os.getcwd() +  relative_path # https://stackoverflow.com/questions/39125532/file-does-not-exist-in-jupyter-notebook
full_path = os.path.join(save_path, file_name)
assert  os.path.exists(full_path), f'Path {relative_path}/{file_name} does not exist'

# read via panda reader
df = pd.read_csv(full_path)
plt.show()
df.plot( figsize=(40, 20), subplots=True)