In [1]:
import numpy as np

In [2]:
import numpy as np

X1 = np.arange(5)
X2 = np.arange(3)
print(X1, X2)
# [0 1 2 3 4] [0 1 2]

def my_op(x, y):
  return x + y

print(X1[:, np.newaxis])

np.vectorize(my_op)(X1[:, np.newaxis], X2)

[0 1 2 3 4] [0 1 2]
[[0]
 [1]
 [2]
 [3]
 [4]]


array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4],
       [3, 4, 5],
       [4, 5, 6]])

In [23]:
x = np.array([1, 2])
x = np.tile(x[:, np.newaxis], 3).ravel()
x

array([1, 1, 1, 2, 2, 2])

In [30]:
x = np.array([1,2,3,4,5,6,7,8])
x = np.repeat(x, 3)
x

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 4, 4, 4, 5, 5, 5, 6, 6, 6, 7, 7, 7, 8,
       8, 8])

In [29]:
x = np.array([1,2])
x = np.repeat(x, 3)
x

array([1, 1, 1, 2, 2, 2])

In [26]:
x = np.array([1,2])
x = np.repeat(x[:, np.newaxis], 3).ravel()
x

array([1, 1, 1, 2, 2, 2])

In [3]:
def MF(x, center, width):
    return x+center#np.exp(-0.5*(((x-center)/width)**2))
    

In [38]:
multiplicator = np.arange(3)
multiplicator = np.tile(np.arange(3), 2)
multiplicator

array([0, 1, 2, 0, 1, 2])

In [57]:
def center_init(x, n_mfs):
    """Initializes the centers of MFs by partitioning the domain of the inputs

    Args:
        x (numpy.ndarray): the max values for each feature, i.e. the domain
        n_mfs (int): number of MFs in Fuzzification Layer
    """
    n_inputs = x.size // n_mfs
    multiplicator = np.arange(1, n_mfs + 1).repeat(n_inputs)
    centers = (x / (n_mfs + 1)) * multiplicator
    return centers

x = np.array([8,10])
x = np.repeat(x, 3)
print(type(x))
print(center_init(x, 3))
print(type(center_init(x, 3))) # numpy.ndarray'

<class 'numpy.ndarray'>
[2.  2.  4.  5.  7.5 7.5]
<class 'numpy.ndarray'>


In [67]:
x = np.array([8,10])
x = np.repeat(x, 3)

def center_init(x, n_mfs):
    """Initializes the centers of MFs by partitioning the domain of the features

    Args:
        x (numpy.ndarray): the max values for each feature, i.e. the domain
        n_mfs (int): number of MFs in Fuzzification Layer
        
    Returns: 
        numpy.ndarray: initalized widths with the shape (x.size,)
    """
    n_inputs = x.size // n_mfs
    multiplicator = np.tile(np.arange(1, n_mfs + 1), n_inputs)
    return (x / (n_mfs + 1)) * multiplicator

x = np.array([8,10])
x = np.repeat(x, 3)
print(type(x))
print(center_init(x, 3))
print(type(center_init(x, 3))) # numpy.ndarray'

<class 'numpy.ndarray'>
[2.  4.  6.  2.5 5.  7.5]
<class 'numpy.ndarray'>


In [69]:
def widths_init(x, n_mfs):
    """Initializes the widths of MFs by partitioning the domain of the features

    Args:
        x (numpy.ndarray): the max values for each feature, i.e. the feature's domain
        n_mfs (int): number of MFs in Fuzzification Layer

    Returns: 
        numpy.ndarray: initalized widths with the shape (x.size,)
    """
    return x/(n_mfs+1)

x = np.array([8,10])
x = np.repeat(x, 3)
print(x.size)
print(widths_init(x, 3))
print(widths_init(x, 3).shape)

6
[2.  2.  2.  2.5 2.5 2.5]
(6,)


In [31]:
x = np.array([1,2])
x = np.repeat(x, 3)

center = np.array([1, 2, 3, 4, 5, 6])# np.ones(3)
width = np.array([1, 2, 3, 4, 5, 6])

print(x)

np.vectorize(MF)(x, center, width)

[1 1 1 2 2 2]


array([2, 3, 4, 6, 7, 8])

In [ ]:
fuzzified_inputs=np.empty(shape=(1, self.n_mfs))

# calculating the MF values μ "mus" per input
for xID, x in enumerate(inputs):

    fuzzified_x = np.vectorize(MF_vec)(x, self.centers[xID], self.widths[xID])
    np.append(fuzzified_inputs,fuzzified_x , axis=0)