Try out for vectorization

In [1]:
import numpy as np

#### How to stretch np arrays so row wise mult will be possible

In [83]:
x = np.array([1, 2])
x = np.tile(x[:, np.newaxis], 3).ravel()
x

array([1, 1, 1, 2, 2, 2])

In [84]:
x = np.array([1,2])
x = np.repeat(x, 3)
x

array([1, 1, 1, 2, 2, 2])

### Fuzzification Layer

In [86]:
multiplicator = np.arange(3)
multiplicator = np.tile(np.arange(3), 2)
multiplicator

array([0, 1, 2, 0, 1, 2])

In [88]:
def center_init(x, n_mfs):
    """Initializes the centers of MFs by partitioning the domain of the features

    Args:
        x (numpy.ndarray): the max values for each feature, i.e. the domain
        n_mfs (int): number of MFs in Fuzzification Layer
        
    Returns: 
        numpy.ndarray: initalized widths with the shape (x.size,)
    """
    n_inputs = x.size // n_mfs
    multiplicator = np.tile(np.arange(1, n_mfs + 1), n_inputs)
    return (x / (n_mfs + 1)) * multiplicator

x = np.array([8,10])
x = np.repeat(x, 3)
print(type(x))
print(center_init(x, 3))
print(type(center_init(x, 3))) # numpy.ndarray'

<class 'numpy.ndarray'>
[2.  4.  6.  2.5 5.  7.5]
<class 'numpy.ndarray'>


In [89]:
def widths_init(x, n_mfs):
    """Initializes the widths of MFs by partitioning the domain of the features

    Args:
        x (numpy.ndarray): the max values for each feature, i.e. the feature's domain
        n_mfs (int): number of MFs in Fuzzification Layer

    Returns: 
        numpy.ndarray: initalized widths with the shape (x.size,)
    """
    return x/(n_mfs+1)

x = np.array([8,10])
x = np.repeat(x, 3)
print(x.size)
print(widths_init(x, 3))
print(widths_init(x, 3).shape)

6
[2.  2.  2.  2.5 2.5 2.5]
(6,)


In [90]:
def MF(x, center, width):
    return np.exp(-0.5*(((x-center)/width)**2))
    

In [91]:
x = np.array([1,2])
x = np.repeat(x, 3)

center = np.array([1, 2, 3, 4, 5, 6])# np.ones(3)
width = np.array([1, 2, 3, 4, 5, 6])

print(x)

MF(x, center, width)

[1 1 1 2 2 2]


array([1.        , 0.8824969 , 0.8007374 , 0.8824969 , 0.83527021,
       0.8007374 ])

### Rule Antecedent Layer


In [105]:
x = np.array([1,2,3,4,5,6])
#x = np.array([1,2,3,4,5,6,7,8,9,10,11,12])


np.array_split(x, range(3, len(x), 3))

[array([1, 2, 3]), array([4, 5, 6])]

In [110]:
x1 = np.array([1,2,3])
x2 = np.array([4,5,6])


x =  np.meshgrid(x1, x2)
print(x)
x = (x[0] * x[1]).ravel()

x

[array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]]), array([[4, 4, 4],
       [5, 5, 5],
       [6, 6, 6]])]


array([ 4,  8, 12,  5, 10, 15,  6, 12, 18])

In [116]:
x = np.array([1,2,3,4,5,6,7,8,9,10,11,12])

x = np.array_split(x, range(3, len(x), 3))
print(x)

x =  np.meshgrid(x[0], x[1], x[2])
#print(x)
x = (x[0] * x[1]).ravel()
x

[array([1, 2, 3]), array([4, 5, 6]), array([7, 8, 9]), array([10, 11, 12])]


array([ 4,  4,  4,  8,  8,  8, 12, 12, 12,  5,  5,  5, 10, 10, 10, 15, 15,
       15,  6,  6,  6, 12, 12, 12, 18, 18, 18])

### rule consequent layer

In [124]:
x = np.array([1,2,3,4,5,6,7,8,9], dtype=np.float64)
weights = np.zeros((x.shape[0], 2), dtype=np.float64)
print(x)
print(weights)

x = x[:, np.newaxis]
print(x)

x*=weights
x

[1. 2. 3. 4. 5. 6. 7. 8. 9.]
[[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]
[1. 2. 3. 4. 5. 6. 7. 8. 9.]


ValueError: operands could not be broadcast together with shapes (9,) (9,2) (9,) 